# Generated by Django 4.2.7 on 2023-11-14 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_bebidas_limpieza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despensa',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='despensa',
            name='biografia',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
