# Generated by Django 4.2.7 on 2023-11-16 13:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('vencimiento', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
    ]
